# ================== mysql ===========================
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.200.112:3306/suphowe?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root

# DataSource Druid数据源
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.200.112:3306/suphowe?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: root
      filters: stat,wall,log4j,config                   # 配置监控统计拦截的filters,去掉后监控界面SQL无法进行统计,'wall'用于防火墙
      max-active: 100                                   # 最大连接数
      initial-size: 1                                   # 初始化大小
      max-wait: 60000                                   # 获取连接等待超时时间
      min-idle: 1                                       # 最小连接数
      time-between-eviction-runs-millis: 60000          # 间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      min-evictable-idle-time-millis: 300000            # 一个连接在池中最小生存的时间,单位是毫秒
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
# ================== 编码 ==========================
  http:
    encoding:
      charset: UTF-8
# ================== server ==========================
server:
  port: 8080
# ===================mybatis========================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.soft.entity

# ===============引入日志配置文件  log  =============================
logging:
  config: classpath:system/logback-boot.xml